import { sortIntentions } from '@shared/lib/roadmap';
import { Link } from 'react-router-dom';
import type { WorkspaceProjection } from '@shared/types/workspace';
import MarkdownRenderer from '@/components/MarkdownRenderer';
import { Button } from '@/components/ui/button';
export default function OutcomeList({workspace:w,expanded,onToggle,onEdit,onCreate}:{onCreate?:(id:string)=>void;workspace:WorkspaceProjection;expanded:Set<string>;onToggle:(id:string)=>void;onEdit:(id:string,outcome:string)=>void}) {
  if(!w.active_intention_ids.length)return <p className="rounded-lg border bg-white p-6 text-stone-600">Define your first intention to describe the outcome this product should achieve.</p>;
  return <ul className="space-y-3">{sortIntentions(Array.from(new Map(w.intentions.map(i=>[i.data.id,i])).values()).filter(i=>w.active_intention_ids.includes(i.data.id))).map(({data:i})=>{
    const activeIds=new Set([...w.coverage.covered_ids,...w.coverage.uncovered_ids]);
    const children=Array.from(new Map(w.expectations.map(e=>[e.data.id,e])).values()).filter(e=>activeIds.has(e.data.id)&&e.data.intention_id===i.id);
    const ids=new Set(children.map(e=>e.data.id));
    const deliveryIds=new Set(Object.values(w.delivery).flat());
    const specs=Array.from(new Map(w.specs.map(s=>[s.data.id,s])).values()).filter(s=>deliveryIds.has(s.data.id)&&(w.spec_expectation_ids[s.data.id]?.some(id=>ids.has(id))||s.data.intentions?.includes(i.id)));
    const phaseCounts=Object.entries(w.delivery).map(([phase,phaseIds])=>({phase,count:specs.filter(s=>phaseIds.includes(s.data.id)).length})).filter(p=>p.count);
    const covered=children.filter(e=>w.coverage.covered_ids.includes(e.data.id)).length;
    return <li key={i.id} className="overflow-hidden rounded-lg border border-stone-200 bg-white"><div className="flex items-start gap-3 p-5"><button className="mt-2 rounded px-2 text-xl text-emerald-800 focus-visible:outline-emerald-700" aria-label={`${expanded.has(i.id)?'Collapse':'Expand'} ${i.title}`} aria-expanded={expanded.has(i.id)} aria-controls={`outcome-${i.id}`} onClick={()=>onToggle(i.id)}>{expanded.has(i.id)?'⌄':'›'}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2 text-xs text-stone-500"><Link to={`/intentions/${i.id}`}>{i.id}</Link><span className="rounded bg-emerald-50 px-2 py-1 text-emerald-800">{i.roadmap?.bucket??'Unscheduled'}</span><span>{i.priority}</span><span>{i.status}</span></div><h3 className="my-2 font-semibold">{i.title}</h3><div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-stone-500"><Link to={`?outcome=${i.id}&concern=coverage`}>{covered} of {children.length} covered</Link><Link to={`?outcome=${i.id}&concern=delivery`}>{specs.length} unique specs</Link>{phaseCounts.map(p=><Link key={p.phase} to={`?outcome=${i.id}&concern=delivery&phase=${encodeURIComponent(p.phase)}`}>{p.count} {p.phase}</Link>)}{!phaseCounts.length&&<span>No delivery yet</span>}<Link to={`?outcome=${i.id}&concern=validation`}>Evidence unknown</Link></div></div></div>
      {expanded.has(i.id)&&<section id={`outcome-${i.id}`} className="border-t bg-stone-50/70 py-2 pl-7 pr-4">{onCreate&&<Button className="my-2" variant="outline" onClick={()=>onCreate(i.id)}>New expectation</Button>}<ul aria-label={`${i.id} expectations`}>{children.map(({data:e})=><li key={e.id} className="relative flex items-start gap-3 border-l-2 border-emerald-200 py-4 pl-5 before:absolute before:left-0 before:top-7 before:w-3 before:border-t-2 before:border-emerald-200"><div className="min-w-0 flex-1"><Link to={`/expectations/${e.id}`} className="text-xs text-stone-500">{e.id}</Link><MarkdownRenderer content={e.description||e.title} variant="inline"/><p className="mt-1 text-xs text-stone-500">{e.status==='Validated'?'Reported validated · evidence unknown':e.status}</p><div className="mt-2 flex flex-wrap gap-2 text-xs">{specs.filter(s=>w.spec_expectation_ids[s.data.id]?.includes(e.id)).map(s=><Link key={s.data.id} to={`/specs/${s.data.id}`} className="rounded bg-white px-2 py-1 text-emerald-800">{s.data.id} · {s.data.phase}</Link>)}{!w.coverage.covered_ids.includes(e.id)&&<span className="text-amber-800">No linked spec</span>}</div></div><Button variant="outline" size="sm" aria-label={`Edit ${e.id}`} onClick={()=>onEdit(e.id,i.id)}>Edit ↗</Button></li>)}</ul>{specs.some(s=>s.data.intentions?.includes(i.id))&&<div className="py-3 text-xs text-stone-600"><p>Direct intention links · do not grant expectation coverage</p>{specs.filter(s=>s.data.intentions?.includes(i.id)).map(s=><Link key={s.data.id} className="mr-3 text-emerald-800" to={`/specs/${s.data.id}`}>{s.data.id} · {s.data.phase}</Link>)}</div>}{!children.length&&<p className="py-4 text-sm text-stone-500">No expectations defined for this outcome.</p>}</section>}
    </li>;
  })}</ul>;
}
