import { useLayoutEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import type { WorkspaceProjection } from '@shared/types/workspace';
import type { Intention, RoadmapPatch } from '@shared/types/intention';
import type { Versioned } from '@shared/types/source';
import { rankBetween, readRoadmap, sortIntentions } from '@shared/lib/roadmap';
import MarkdownRenderer from '@/components/MarkdownRenderer';
import { Button } from '@/components/ui/button';
const columns = ['now','next','later','unscheduled'] as const;
const labels = {now:'Now',next:'Next',later:'Later',unscheduled:'Unscheduled'};
export default function RoadmapBoard({workspace:w,onMove,onEdit}:{workspace:WorkspaceProjection;onMove:(id:string,patch:RoadmapPatch,revision:string)=>Promise<void>;onEdit?:(id:string)=>void}) {
  const [completed,setCompleted]=useState(false),[archived,setArchived]=useState(false),[pending,setPending]=useState<string|null>(null),[error,setError]=useState('');
  const [replace,setReplace]=useState<string|null>(null),[windowEdit,setWindowEdit]=useState<string|null>(null),[windowValue,setWindowValue]=useState('');
  const busy=useRef(false), restoreFocus=useRef<string|null>(null);
  useLayoutEffect(()=>{if(!pending&&restoreFocus.current){document.getElementById(restoreFocus.current)?.focus();restoreFocus.current=null;}},[pending,w]);
  const all = sortIntentions([...new Map(w.intentions.filter(r=>r.data.product_id===w.product.data.id).map(r=>[r.data.id,r])).values()]);
  const visible = all.filter(r=>(archived||!r.data.archived_at)&&(completed||!['fulfilled','done','completed'].includes(r.data.status.toLowerCase())));
  function unsupported(i:Intention){const forge=i.extras.forge;return readRoadmap(forge&&typeof forge==='object'?(forge as Record<string,unknown>).roadmap:i.roadmap).unsupported;}
  async function apply(record:Versioned<Intention>,patch:RoadmapPatch){if(busy.current)return;busy.current=true;const active=document.activeElement;if(active instanceof HTMLElement&&active.id===`move-${record.data.id}`)restoreFocus.current=active.id;setPending(record.data.id);setError('');try{await onMove(record.data.id,patch,record.source.revision);setReplace(null);setWindowEdit(null);}catch(e){setError(e instanceof Error?e.message:'Could not save planning. Reload the source and retry.');}finally{busy.current=false;setPending(null);}}
  function move(record:Versioned<Intention>,destination:string){try{if(destination==='unscheduled'){void apply(record,{bucket:null});return;}const peers=all.filter(r=>r.data.id!==record.data.id&&r.data.roadmap?.bucket===destination);const last=peers.filter(r=>Number.isFinite(r.data.roadmap?.rank)).at(-1);void apply(record,{bucket:destination as 'now'|'next'|'later',rank:rankBetween(last?.data.roadmap?.rank??null,null)});}catch(e){setError((e as Error).message);}}
  function reorder(record:Versioned<Intention>,direction:-1|1){try{const bucket=record.data.roadmap?.bucket;const peers=all.filter(r=>r.data.roadmap?.bucket===bucket);const index=peers.findIndex(r=>r.data.id===record.data.id);const destination=index+direction;if(destination<0||destination>=peers.length)return;const without=peers.filter(r=>r.data.id!==record.data.id);if(destination>0&&!Number.isFinite(without[destination-1]?.data.roadmap?.rank))throw new Error('This position follows an unranked outcome. Choose a position before ranked outcomes or move to another column.');const before=without[destination-1]?.data.roadmap?.rank??null,after=without[destination]?.data.roadmap?.rank??null;void apply(record,{rank:rankBetween(before,after)});}catch(e){setError((e as Error).message);}}
  return <section aria-label="Roadmap"><div className="flex flex-wrap gap-5 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={completed} onChange={e=>setCompleted(e.target.checked)}/>Show completed</label><label className="flex items-center gap-2"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Show archived</label></div>
    <p className="my-4 text-sm text-stone-600">Planning placement never changes delivery phase or intention status. Target windows are labels entered by your team.</p>{error&&<p role="alert" className="mb-4 rounded border border-red-200 p-3 text-sm text-red-800">{error}</p>}
    <div className="grid items-start gap-4 sm:grid-cols-2 xl:grid-cols-4">{columns.map(bucket=><section key={bucket} aria-label={labels[bucket]} className="min-w-0 rounded-lg bg-stone-100 p-3"><h2 className="mb-4 text-sm font-semibold">{labels[bucket]}</h2><div className="space-y-3">{visible.filter(r=>(r.data.roadmap?.bucket??'unscheduled')===bucket).map(record=>{const i=record.data,unknown=unsupported(i);const readonly=record.source.read_only_fields['*']||record.source.read_only_fields.roadmap;const blocked=!!readonly&&!readonly.startsWith('Unsupported roadmap metadata.');const disabled=pending!==null||blocked;const peers=all.filter(r=>(r.data.roadmap?.bucket??'unscheduled')===bucket);const index=peers.findIndex(r=>r.data.id===i.id);return <article key={i.id} className="min-w-0 space-y-3 rounded-lg border bg-white p-4 shadow-sm"><p className="text-xs text-stone-500">{i.id} · {i.status}{i.archived_at?' · Archived':''}</p><h3 className="break-words font-semibold"><Link to={`/intentions/${i.id}`}>{i.title}</Link></h3><div className="flex flex-wrap gap-2 text-xs"><span className="rounded bg-emerald-50 px-2 py-1 text-emerald-900">{i.priority}</span><span>{i.owner||'Owner unassigned'}</span></div>{i.rationale&&<div className="text-sm text-stone-600"><MarkdownRenderer content={i.rationale} variant="inline"/></div>}
      {(w.intention_dependency_ids[i.id]??[]).map((id,n)=>{const dep=w.intentions.find(r=>r.data.id===id)?.data;return <p className="text-xs" key={`${id}:${n}`}>Depends on <Link className="text-emerald-800 underline" to={`/intentions/${id}`}>{dep?.title??id}</Link> · {dep?.status??'Missing source'}{dep&&dep.product_id!==i.product_id?' · Outside this product':''}</p>;})}
      <div className="text-xs text-stone-600">Target window: {i.roadmap?.target_window?<span className="break-words">{i.roadmap.target_window}</span>:'Not set'}</div>
      {unknown?<div className="space-y-2 rounded border border-amber-200 p-2 text-xs"><p>Unsupported planning metadata is preserved in the source.</p><Button size="sm" variant="outline" disabled={disabled} onClick={()=>setReplace(i.id)}>Replace planning metadata</Button>{replace===i.id&&<div><p>This replaces unsupported planning fields. Other source fields remain intact.</p><Button size="sm" disabled={disabled} onClick={()=>void apply(record,{bucket:null})}>Confirm replacement</Button><Button size="sm" variant="ghost" onClick={()=>setReplace(null)}>Cancel</Button></div>}</div>:<><label className="block text-xs" htmlFor={`move-${i.id}`}>Move {i.id}</label><select id={`move-${i.id}`} className="w-full rounded border bg-white p-2 text-sm" value={bucket} disabled={disabled} onChange={e=>move(record,e.target.value)}>{columns.map(c=><option key={c} value={c}>{labels[c]}</option>)}</select><div className="flex flex-wrap gap-1"><Button size="sm" variant="outline" aria-label={`Move ${i.id} earlier`} disabled={disabled||index===0} onClick={()=>reorder(record,-1)}>↑ Earlier</Button><Button size="sm" variant="outline" aria-label={`Move ${i.id} later`} disabled={disabled||index===peers.length-1} onClick={()=>reorder(record,1)}>↓ Later</Button></div><Button size="sm" variant="ghost" disabled={disabled} onClick={()=>{setWindowEdit(i.id);setWindowValue(i.roadmap?.target_window??'');}}>Edit target window</Button>{windowEdit===i.id&&<div className="space-y-2"><label className="block text-xs">Target window<input className="mt-1 w-full rounded border p-2" value={windowValue} onChange={e=>setWindowValue(e.target.value)}/></label><Button size="sm" disabled={disabled} onClick={()=>void apply(record,{target_window:windowValue||null})}>Save target window</Button><Button size="sm" variant="ghost" onClick={()=>setWindowEdit(null)}>Cancel</Button></div>}</>}
      {blocked&&<p className="text-xs text-amber-800">{readonly} <Link to={`/intentions/${i.id}?yaml=1`}>Review source</Link></p>}{onEdit&&<Button size="sm" variant="ghost" onClick={()=>onEdit(i.id)}>Edit outcome</Button>}{pending===i.id&&<p role="status" className="text-xs">Saving planning…</p>}
    </article>;})}{!visible.some(r=>(r.data.roadmap?.bucket??'unscheduled')===bucket)&&<p className="py-8 text-sm text-stone-500">No outcomes placed here.</p>}</div></section>)}</div>
  </section>;
}
